version: '3.8'
services:
  web:
    build: .
    ports:
        - "3000:80"
    volumes:
        - .:/app
        - /app/node_modules
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5